# Generated by Django 4.2.7 on 2023-11-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_is_published_listing_ispublished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='zip',
        ),
    ]
