# Generated by Django 4.2.7 on 2023-11-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0004_alter_listing_realtor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='garage',
            new_name='garages',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='isPublished',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(db_column='realtor_id_id', on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(),
        ),
    ]
