# Generated by Django 4.2.7 on 2023-11-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_address_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='garages',
            field=models.IntegerField(),
        ),
    ]
